import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <section style={{ background: 'linear-gradient(165deg, #0a1628, #1a2d4a)', padding: '80px 24px 60px' }}>
        <div style={{ maxWidth: 720, margin: '0 auto' }}>
          <h1 style={{ fontSize: 36, fontWeight: 700, color: '#fff', margin: 0 }}>Terms of Use</h1>
          <p style={{ fontSize: 14, color: '#94a3b8', marginTop: 8 }}>Last updated: March 25, 2026</p>
        </div>
      </section>
      <section style={{ padding: '48px 24px 80px' }}>
        <div style={{ maxWidth: 720, margin: '0 auto', background: '#fff', border: '1px solid #e2e8f0', borderRadius: 14, padding: '40px 44px' }}>
          {[
            ['Acceptance of terms', 'By accessing or using hccsstandard.com (the "Website"), you agree to these Terms of Use. If you do not agree, do not use the Website. These terms constitute a legal agreement between you and IngenuityCo LLC ("we," "us," "our").'],
            ['Description of services', 'The Website provides information about the Human Capital Control Standard™ (HCCS™), including governance assessments, educational content, downloadable documents, fillable templates, an AI-powered chat assistant, and related tools and resources.'],
            ['Intellectual property', `The HCCS™ Standard, including all documents, controls, assessment instruments, templates, blog content, and website design, is the intellectual property of IngenuityCo LLC. "HCCS" and "Human Capital Control Standard" are trademarks of IngenuityCo LLC.

You may not reproduce, distribute, modify, create derivative works from, or commercially exploit any content from this Website without prior written permission, except for:
• Downloading documents for your organization's internal use
• Generating and sharing assessment reports and business case documents for internal decision-making
• Referencing the standard with proper attribution`],
            ['Assessment services', `Self-Assessment and Guided Assessment services are provided as-is. Assessment results reflect the information you provide and do not constitute legal advice, certified compliance, or third-party validation unless explicitly stated.

Self-Assessment results are generated from your self-reported answers. They are intended for internal planning and gap identification. They do not represent a validated audit.

Guided Assessment and Enterprise engagements are subject to separate agreements executed at the time of purchase.`],
            ['User conduct', `When using our services, you agree to:
• Provide accurate information in assessments and forms
• Use the services for their intended purpose (organizational governance assessment)
• Not attempt to circumvent access controls, payment requirements, or security measures
• Not use the AI chat assistant to generate harmful, misleading, or inappropriate content
• Not scrape, crawl, or automated-extract content from the Website`],
            ['Payments and refunds', 'Payments for assessments are processed through Stripe. All sales are final. If you experience a technical issue that prevents you from completing a purchased assessment, contact us and we will work to resolve it or provide a replacement access code.'],
            ['AI chat assistant', 'The AI-powered chat assistant provides general information about the HCCS™ Standard. It does not provide legal, financial, or professional advice. Responses are generated by a third-party AI model and may occasionally be incomplete or imperfect. Do not rely on chat responses as a substitute for professional consultation.'],
            ['Limitation of liability', 'To the maximum extent permitted by law, IngenuityCo LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Website or services. Our total liability for any claim related to the services shall not exceed the amount you paid for the specific service giving rise to the claim.'],
            ['Disclaimer of warranties', 'The Website and services are provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.'],
            ['Indemnification', 'You agree to indemnify and hold harmless IngenuityCo LLC, its officers, directors, and agents from any claims, damages, or expenses arising from your use of the Website or violation of these terms.'],
            ['Governing law', 'These terms are governed by the laws of the State of Arizona, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Maricopa County, Arizona.'],
            ['Changes to terms', 'We may update these terms from time to time. Continued use of the Website after changes are posted constitutes acceptance of the updated terms.'],
            ['Contact', 'For questions about these terms, contact us via the contact form at hccsstandard.com/contact.'],
          ].map(([title, text]) => (
            <div key={title} style={{ marginBottom: 28 }}>
              <h2 style={{ fontSize: 18, fontWeight: 700, color: '#0f172a', margin: '0 0 8px' }}>{title}</h2>
              <p style={{ fontSize: 15, lineHeight: 1.7, color: '#475569', margin: 0, whiteSpace: 'pre-line' }}>{text}</p>
            </div>
          ))}
          <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: 20, marginTop: 32 }}>
            <p style={{ fontSize: 13, color: '#94a3b8' }}>© 2026 IngenuityCo LLC. All rights reserved.</p>
          </div>
        </div>
      </section>
    </div>
  )
}
